name: quickbib
version: '0.4.1'
summary: "Quickly get BibTeX from a DOI"
description: |
  QuickBib is a small cross-platform desktop app that retrieves the BibTeX
  entry for a publication from its DOI (Digital Object Identifier). It
  supports DOIs, arXiv IDs and many journal URLs and uses the doi2bib3 library
  as its backend to fetch and format BibTeX entries.
title: QuickBib
contact: https://github.com/archisman-panigrahi/QuickBib
license: GPL-3.0-only
website: https://archisman-panigrahi.github.io/QuickBib/
source-code: https://github.com/archisman-panigrahi/QuickBib
issues: https://github.com/archisman-panigrahi/QuickBib/issues
grade: stable
confinement: strict
base: core24
compression: lzo


apps:
  quickbib:
    command: usr/bin/quickbib
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt6/plugins
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms
      # SNAP_DESKTOP_RUNTIME: $SNAP/kf6
      # QT_VERSION: "6"
      # XDG_DATA_DIRS: $SNAP/usr/share:${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    plugs:
      - network
      - x11
      - wayland

parts:
  quickbib:
    plugin: meson
    # Track the latest code from the GitHub repository (HEAD of `main` branch).
    # Use a shallow clone (source-depth: 1) to fetch the latest commit quickly.
    source: https://github.com/archisman-panigrahi/QuickBib.git
    source-branch: main
    source-depth: 1
    build-packages:
      - python3-dev
      - pkg-config
      - build-essential
      - meson
      - ninja-build
    stage-packages:
      - python3
      - python3-pyqt6
    meson-parameters:
      - --prefix=/snap/quickbib/current/usr
      - -Dbuildtype=release
    organize:
      snap/quickbib/current: .

  python-deps:
    plugin: python
    source: ..
    python-packages:
      - doi2bib3
    stage-packages:
      - python3

lint:
  ignore:
    - classic
    - library:
      - usr/lib/**/lib*.so*
    - metadata:
      - donation
