name: quickbib
version: '0.4.1'
summary: "Quickly get BibTeX from a DOI"
description: |
  QuickBib is a small cross-platform desktop app that retrieves the BibTeX
  entry for a publication from its DOI (Digital Object Identifier). It
  supports DOIs, arXiv IDs and many journal URLs and uses the doi2bib3 library
  as its backend to fetch and format BibTeX entries.
title: QuickBib
contact: https://github.com/archisman-panigrahi/QuickBib
license: GPL-3.0-only
website: https://archisman-panigrahi.github.io/QuickBib/
source-code: https://github.com/archisman-panigrahi/QuickBib
issues: https://github.com/archisman-panigrahi/QuickBib/issues
grade: stable
confinement: strict
base: core24
compression: lzo


apps:
  quickbib:
    command: usr/bin/quickbib
    desktop: usr/share/applications/io.github.archisman_panigrahi.QuickBib.desktop
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]

plugs:
  lxqt-support:
    content: lxqt-support
    interface: content
    target: $SNAP/lxqt-support
    default-provider: lxqt-support

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support/usr/share/Kvantum

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/apandada1/quickbib/ubuntu
    suites: [noble]
    components: [main]
    architectures: [arm64, amd64, armhf, ppc64el, riscv64, s390x]
    key-id: 4BDCA6FAF8BE2B807944B40C9E776C57AA2476B8

parts:
  quickbib:
    plugin: nil
    stage-packages:
      - quickbib
      - python3-doi2bib3
      - python3-pyqt6
      - python3-bibtexparser
      - python3-pyparsing
    override-build: |
      craftctl default
      sed -e 's|Exec=quickbib %U|Exec=${SNAP}/usr/bin/quickbib %U|' -i  $CRAFT_PART_INSTALL/usr/share/applications/io.github.archisman_panigrahi.QuickBib.desktop
      sed -e 's|Icon=io.github.archisman_panigrahi.QuickBib|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/io.github.archisman_panigrahi.QuickBib.svg|' -i  $CRAFT_PART_INSTALL/usr/share/applications/io.github.archisman_panigrahi.QuickBib.desktop
    prime:
      - usr/bin/doi2bib3
      - usr/bin/quickbib
      - usr/lib/python3/dist-packages/doi2bib3
      - usr/lib/python3/dist-packages/PyQt6
      - usr/lib/python3/dist-packages/bibtexparser
      - usr/lib/python3/dist-packages/pyparsing
      - usr/share/applications/io.github.archisman_panigrahi.QuickBib.desktop
      - usr/share/doc/python3-doi2bib3
      - usr/share/doc/quickbib
      - usr/share/icons/hicolor/*/apps/io.github.archisman_panigrahi.QuickBib.svg
      - usr/share/metainfo/io.github.archisman_panigrahi.QuickBib.metainfo.xml
      - usr/share/python3/runtime.d/quickbib.rtupdate
      - usr/share/quickbib

lint:
  ignore:
    - classic
    - library:
      - usr/lib/**/lib*.so*
    - metadata:
      - donation
