name: Windows packaging

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install NSIS (if needed)
        shell: powershell
        run: |
          choco install nsis -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Install project requirements; requirements.txt references doi2bib3 via git+https
          pip install -r requirements.txt

      - name: Build with PyInstaller (use spec)
        shell: bash
        run: |
          # Use the repo's PyInstaller spec to collect PyQt6 plugins and assets.
          pyinstaller --noconfirm quickbib.spec

      - name: Show dist contents
        run: |
          ls -la dist || true

      - name: Create installer with NSIS
        shell: powershell
        run: |
          # makensis should be on PATH after choco install
          makensis windows_packaging\quickbib.nsi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickBib-windows-installer
          path: QuickBib-Installer.exe

      - name: Create GitHub Release and upload installer (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: QuickBib-Installer.exe
