name: Windows packaging

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install NSIS (if needed)
        shell: powershell
        run: |
          choco install nsis -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Install project requirements; requirements.txt references doi2bib3 via git+https
          pip install -r requirements.txt

      - name: Build with PyInstaller (use spec)
        # Use PowerShell on the Windows runner to avoid path/translation issues with Git Bash
        shell: pwsh
        run: |
          # Debug: show current working directory and workspace contents so we can diagnose
          # why the spec file isn't visible to PyInstaller on the runner.
          Write-Host "GITHUB_WORKSPACE=$env:GITHUB_WORKSPACE"
          Write-Host "Current directory:"
          pwd
          Write-Host "Listing current directory contents:"
          Get-ChildItem -Force
          Write-Host "Listing GITHUB_WORKSPACE contents:"
          Get-ChildItem -Path $env:GITHUB_WORKSPACE -Force

          # Run PyInstaller using an absolute Windows path to the spec to avoid cwd/path issues.
          python -m PyInstaller --noconfirm "$env:GITHUB_WORKSPACE\quickbib.spec"

      - name: Show dist contents
        run: |
          ls -la dist || true

      - name: Create installer with NSIS
        shell: powershell
        run: |
          # makensis should be on PATH after choco install
          makensis windows_packaging\quickbib.nsi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickBib-windows-installer
          path: QuickBib-Installer.exe

      - name: Create GitHub Release and upload installer (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: QuickBib-Installer.exe
